networks:
  walmannet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.48.0.0/16

services:
  walmandbserver:
    build: ./walmandbserver
    extra_hosts:
      - "walmandbclient1.example.com:172.48.0.122"
      - "walmandbclient2.example.com:172.48.0.123"
    hostname: walmandbserver.example.com
    networks:
      walmannet:
        ipv4_address: 172.48.0.121
    ports:
      - name: ssh
        target: 22
        published: 55121
    tty: true

  walmandbclient1:
    build: ./walmandbclient1
    extra_hosts:
      - "walmandbclient2.example.com:172.48.0.123"
      - "walmandbserver.example.com:172.48.0.121"
    hostname: walmandbclient1.example.com
    networks:
      walmannet:
       ipv4_address: 172.48.0.122
    ports:
      - name: ssh
        target: 22
        published: 55122
    tty: true

  walmandbclient2:
    build: ./walmandbclient2
    extra_hosts:
      - "walmandbclient1.example.com:172.48.0.122"
      - "walmandbserver.example.com:172.48.0.121"
    hostname: walmandbclient2.example.com
    networks:
      walmannet:
        ipv4_address: 172.48.0.123
    ports:
      - name: ssh
        target: 22
        published: 55123
    tty: true
